services:
  allhands22:
    image: "${TESTING_IMAGE}"
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      allhands22:
        condition: service_started
      postgres:
        condition: service_healthy
    # run all your tests here against the allhands22 service
    command: curl --fail http://allhands22:80 || exit 1